version: "3.1"
services:
#Base de Datos
    mysqladrianocamp:
        image: mysql
        container_name: MySQLAdrianOcamp
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: AdrianOcamp
            MYSQL_PASSWORD: admin1234
            MYSQL_ROOT_PASSWORD: admin1234 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - 2dw3OcampoSepulveda
# Apache
    apacheadrianocamp:

        build: .
        container_name: ApacheAdrianOcamp
        ports: 
            - 2208:80
        volumes:
            - ./www:/var/www/html
        links:
            - mysqladrianocamp
        networks:
            - 2dw3OcampoSepulveda
# Phpmyadmin
    adminadrianocamp:
        image: phpmyadmin/phpmyadmin
        container_name: AdminAdrianOcamp
        links: 
            - mysqladrianocamp:mysqladrianocamp
        ports:
            - 8008:80
        environment:
            MYSQL_USER: AdrianOcamp
            MYSQL_PASSWORD: admin1234
            MYSQL_ROOT_PASSWORD: admin1234
        networks:
            - 2dw3OcampoSepulveda
volumes:
    persistent:
networks: 
    2dw3OcampoSepulveda:
